version: "3.8"

volumes:
  hdfs-simulado:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - hdfs-simulado:/opt/workspace

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    ports:
      - 8081:8081
    volumes:
      - hdfs-simulado:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    ports:
      - 8082:8081
    volumes:
      - hdfs-simulado:/opt/workspace
    depends_on:
      - spark-master

  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - hdfs-simulado:/opt/workspace
